package org.ventura.sistemafinanciero.entity.type;

public enum Variable {
	TRANSACCION_MAYOR_CUANTIA_NUEVOS_SOLES, 
	TRANSACCION_MAYOR_CUANTIA_DOLARES, 
	TRANSACCION_MAYOR_CUANTIA_EUROS,
	
	TASA_COMPRA_DOLAR,
	TASA_VENTA_DOLAR,
	TASA_COMPRA_EURO,
	TASA_VENTA_EURO
}
