package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agencia generated by hbm2java
 */
@Entity
@Table(name = "AGENCIA", schema = "BDSISTEMAFINANCIERO")
public class Agencia implements java.io.Serializable {

	private BigDecimal idAgencia;
	private Sucursal sucursal;
	private String denominacion;
	private BigDecimal estado;
	private String abreviatura;
	private String ubigeo;
	private Set bovedas = new HashSet(0);
	private Set trabajadors = new HashSet(0);

	public Agencia() {
	}

	public Agencia(BigDecimal idAgencia, Sucursal sucursal,
			String denominacion, BigDecimal estado, String abreviatura,
			String ubigeo) {
		this.idAgencia = idAgencia;
		this.sucursal = sucursal;
		this.denominacion = denominacion;
		this.estado = estado;
		this.abreviatura = abreviatura;
		this.ubigeo = ubigeo;
	}

	public Agencia(BigDecimal idAgencia, Sucursal sucursal,
			String denominacion, BigDecimal estado, String abreviatura,
			String ubigeo, Set bovedas, Set trabajadors) {
		this.idAgencia = idAgencia;
		this.sucursal = sucursal;
		this.denominacion = denominacion;
		this.estado = estado;
		this.abreviatura = abreviatura;
		this.ubigeo = ubigeo;
		this.bovedas = bovedas;
		this.trabajadors = trabajadors;
	}

	@Id
	@Column(name = "ID_AGENCIA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdAgencia() {
		return this.idAgencia;
	}

	public void setIdAgencia(BigDecimal idAgencia) {
		this.idAgencia = idAgencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SUCURSAL", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 100, columnDefinition = "nvarchar2")
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@Column(name = "ABREVIATURA", nullable = false, length = 20, columnDefinition = "nvarchar2")
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "UBIGEO", nullable = false, length = 12, columnDefinition = "nvarchar2")
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agencia")
	public Set<Boveda> getBovedas() {
		return this.bovedas;
	}

	public void setBovedas(Set bovedas) {
		this.bovedas = bovedas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agencia")
	public Set<Trabajador> getTrabajadors() {
		return this.trabajadors;
	}

	public void setTrabajadors(Set trabajadors) {
		this.trabajadors = trabajadors;
	}

}
