package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Beneficiario generated by hbm2java
 */
@Entity
@Table(name = "BENEFICIARIO", schema = "BDSISTEMAFINANCIERO")
@XmlRootElement(name = "beneficiario")
@XmlAccessorType(XmlAccessType.NONE)
public class Beneficiario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idBeneficiario;
	private CuentaBancaria cuentaBancaria;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String nombres;
	private String numeroDocumento;
	private BigDecimal porcentajeBeneficio;

	public Beneficiario() {
	}

	public Beneficiario(BigDecimal idBeneficiario,
			CuentaBancaria cuentaBancaria, BigDecimal porcentajeBeneficio) {
		// this.idBeneficiario = idBeneficiario;
		this.cuentaBancaria = cuentaBancaria;
		this.porcentajeBeneficio = porcentajeBeneficio;
	}

	public Beneficiario(BigDecimal idBeneficiario,
			CuentaBancaria cuentaBancaria, String apellidoPaterno,
			String apellidoMaterno, String nombres, String numeroDocumento,
			BigDecimal porcentajeBeneficio) {
		// this.idBeneficiario = idBeneficiario;
		this.cuentaBancaria = cuentaBancaria;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombres = nombres;
		this.numeroDocumento = numeroDocumento;
		this.porcentajeBeneficio = porcentajeBeneficio;
	}

	@XmlElement
	@Id
	@Column(name = "ID_BENEFICIARIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdBeneficiario() {
		return this.idBeneficiario;
	}

	public void setIdBeneficiario(BigInteger idBeneficiario) {
		this.idBeneficiario = idBeneficiario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTA_BANCARIA", nullable = false)
	public CuentaBancaria getCuentaBancaria() {
		return this.cuentaBancaria;
	}

	public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
		this.cuentaBancaria = cuentaBancaria;
	}

	@Column(name = "APELLIDO_PATERNO", length = 140, columnDefinition = "nvarchar2")
	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	@Column(name = "APELLIDO_MATERNO", length = 140, columnDefinition = "nvarchar2")
	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	@Column(name = "NOMBRES", length = 140, columnDefinition = "nvarchar2")
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "NUMERO_DOCUMENTO", length = 40, columnDefinition = "nvarchar2")
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "PORCENTAJE_BENEFICIO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPorcentajeBeneficio() {
		return this.porcentajeBeneficio;
	}

	public void setPorcentajeBeneficio(BigDecimal porcentajeBeneficio) {
		this.porcentajeBeneficio = porcentajeBeneficio;
	}

}
