package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BovedaCajaId generated by hbm2java
 */
@Embeddable
public class BovedaCajaId implements java.io.Serializable {

	private BigDecimal idBoveda;
	private BigDecimal idCaja;
	private BigDecimal saldo;

	public BovedaCajaId() {
	}

	public BovedaCajaId(BigDecimal idBoveda, BigDecimal idCaja, BigDecimal saldo) {
		this.idBoveda = idBoveda;
		this.idCaja = idCaja;
		this.saldo = saldo;
	}

	@Column(name = "ID_BOVEDA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdBoveda() {
		return this.idBoveda;
	}

	public void setIdBoveda(BigDecimal idBoveda) {
		this.idBoveda = idBoveda;
	}

	@Column(name = "ID_CAJA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(BigDecimal idCaja) {
		this.idCaja = idCaja;
	}

	@Column(name = "SALDO", nullable = false, precision = 18)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BovedaCajaId))
			return false;
		BovedaCajaId castOther = (BovedaCajaId) other;

		return ((this.getIdBoveda() == castOther.getIdBoveda()) || (this
				.getIdBoveda() != null && castOther.getIdBoveda() != null && this
				.getIdBoveda().equals(castOther.getIdBoveda())))
				&& ((this.getIdCaja() == castOther.getIdCaja()) || (this
						.getIdCaja() != null && castOther.getIdCaja() != null && this
						.getIdCaja().equals(castOther.getIdCaja())))
				&& ((this.getSaldo() == castOther.getSaldo()) || (this
						.getSaldo() != null && castOther.getSaldo() != null && this
						.getSaldo().equals(castOther.getSaldo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdBoveda() == null ? 0 : this.getIdBoveda().hashCode());
		result = 37 * result
				+ (getIdCaja() == null ? 0 : this.getIdCaja().hashCode());
		result = 37 * result
				+ (getSaldo() == null ? 0 : this.getSaldo().hashCode());
		return result;
	}

}
