package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Boveda generated by hbm2java
 */
@Entity
@Table(name = "BOVEDA", schema = "BDSISTEMAFINANCIERO")
@XmlRootElement(name = "caja")
@XmlAccessorType(XmlAccessType.NONE)
public class Boveda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int idBoveda;
	private Moneda moneda;
	private Agencia agencia;
	private String denominacion;
	private int estado;
	private int abierto;
	private int estadoMovimiento;
	private Set bovedaCajas = new HashSet(0);
	private Set historialBovedas = new HashSet(0);

	public Boveda() {
	}

	public Boveda(int idBoveda, Moneda moneda, Agencia agencia,
			String denominacion, boolean estado, boolean abierto,
			boolean estadoMovimiento) {
		this.idBoveda = idBoveda;
		this.moneda = moneda;
		this.agencia = agencia;
		this.denominacion = denominacion;
		this.estado = (estado ? 1 : 0);
		this.abierto = (abierto ? 1 : 0);
		this.estadoMovimiento = (estadoMovimiento ? 1 : 0);
	}

	public Boveda(int idBoveda, Moneda moneda, Agencia agencia,
			String denominacion, boolean estado, boolean abierto,
			boolean estadoMovimiento, Set bovedaCajas, Set historialBovedas) {
		this.idBoveda = idBoveda;
		this.moneda = moneda;
		this.agencia = agencia;
		this.denominacion = denominacion;
		this.estado = (estado ? 1 : 0);
		this.abierto = (abierto ? 1 : 0);
		this.estadoMovimiento = (estadoMovimiento ? 1 : 0);
		this.bovedaCajas = bovedaCajas;
		this.historialBovedas = historialBovedas;
	}

	@XmlTransient
	@Id
	@Column(name = "ID_BOVEDA", unique = true, nullable = false, precision = 22, scale = 0)
	public int getIdBoveda() {
		return this.idBoveda;
	}

	public void setIdBoveda(int idBoveda) {
		this.idBoveda = idBoveda;
	}

	@XmlElement
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA", nullable = false)
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@XmlTransient
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AGENCIA", nullable = false)
	public Agencia getAgencia() {
		return this.agencia;
	}

	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	@XmlElement
	@Column(name = "DENOMINACION", nullable = false, length = 100, columnDefinition = "nvarchar2")
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@XmlElement
	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public boolean getEstado() {
		return (this.estado == 1 ? true : false);
	}

	public void setEstado(boolean estado) {
		this.estado = (estado ? 1 : 0);
	}

	@XmlElement
	@Column(name = "ABIERTO", nullable = false, precision = 22, scale = 0)
	public boolean getAbierto() {
		return (this.abierto == 1 ? true : false);
	}

	public void setAbierto(boolean abierto) {
		this.abierto = (abierto ? 1 : 0);
	}

	@XmlElement
	@Column(name = "ESTADO_MOVIMIENTO", nullable = false, precision = 22, scale = 0)
	public boolean getCongelado() {
		return (this.estadoMovimiento == 1 ? true : false);
	}

	public void setCongelado(boolean estadoMovimiento) {
		this.estadoMovimiento = (estadoMovimiento ? 1 : 0);
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boveda")
	public Set<BovedaCaja> getBovedaCajas() {
		return this.bovedaCajas;
	}

	public void setBovedaCajas(Set bovedaCajas) {
		this.bovedaCajas = bovedaCajas;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boveda")
	public Set<HistorialBoveda> getHistorialBovedas() {
		return this.historialBovedas;
	}

	public void setHistorialBovedas(Set historialBovedas) {
		this.historialBovedas = historialBovedas;
	}

}
