package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name = "CAJA", schema = "BDSISTEMAFINANCIERO")
public class Caja implements java.io.Serializable {

	private BigDecimal idCaja;
	private String denominacion;
	private String abreviatura;
	private BigDecimal estado;
	private BigDecimal abierto;
	private BigDecimal estadoMovimiento;
	private Set trabajadorCajas = new HashSet(0);
	private Set bovedaCajas = new HashSet(0);
	private Set historialCajas = new HashSet(0);

	public Caja() {
	}

	public Caja(BigDecimal idCaja, String denominacion, String abreviatura,
			BigDecimal estado, BigDecimal abierto, BigDecimal estadoMovimiento) {
		this.idCaja = idCaja;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.abierto = abierto;
		this.estadoMovimiento = estadoMovimiento;
	}

	public Caja(BigDecimal idCaja, String denominacion, String abreviatura,
			BigDecimal estado, BigDecimal abierto, BigDecimal estadoMovimiento,
			Set trabajadorCajas, Set bovedaCajas, Set historialCajas) {
		this.idCaja = idCaja;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.abierto = abierto;
		this.estadoMovimiento = estadoMovimiento;
		this.trabajadorCajas = trabajadorCajas;
		this.bovedaCajas = bovedaCajas;
		this.historialCajas = historialCajas;
	}

	@Id
	@Column(name = "ID_CAJA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(BigDecimal idCaja) {
		this.idCaja = idCaja;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 40,columnDefinition = "nvarchar2")
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ABREVIATURA", nullable = false, length = 20,columnDefinition = "nvarchar2")
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@Column(name = "ABIERTO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAbierto() {
		return this.abierto;
	}

	public void setAbierto(BigDecimal abierto) {
		this.abierto = abierto;
	}

	@Column(name = "ESTADO_MOVIMIENTO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstadoMovimiento() {
		return this.estadoMovimiento;
	}

	public void setEstadoMovimiento(BigDecimal estadoMovimiento) {
		this.estadoMovimiento = estadoMovimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public Set<TrabajadorCaja> getTrabajadorCajas() {
		return this.trabajadorCajas;
	}

	public void setTrabajadorCajas(Set trabajadorCajas) {
		this.trabajadorCajas = trabajadorCajas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public Set<BovedaCaja> getBovedaCajas() {
		return this.bovedaCajas;
	}

	public void setBovedaCajas(Set bovedaCajas) {
		this.bovedaCajas = bovedaCajas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public Set<HistorialCaja> getHistorialCajas() {
		return this.historialCajas;
	}

	public void setHistorialCajas(Set historialCajas) {
		this.historialCajas = historialCajas;
	}

}
