package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CuentaAporte generated by hbm2java
 */
@Entity
@Table(name = "CUENTA_APORTE", schema = "BDSISTEMAFINANCIERO")
public class CuentaAporte implements java.io.Serializable {

	private BigDecimal idCuentaaporte;
	private BigDecimal saldo;
	private Moneda moneda;
	private String estadoCuenta;
	private Set socios = new HashSet(0);

	public CuentaAporte() {
	}

	public CuentaAporte(BigDecimal idCuentaaporte, BigDecimal saldo,
			String estadoCuenta) {
		this.idCuentaaporte = idCuentaaporte;
		this.saldo = saldo;
		this.estadoCuenta = estadoCuenta;
	}

	public CuentaAporte(BigDecimal idCuentaaporte, BigDecimal saldo,
			String estadoCuenta, Set socios) {
		this.idCuentaaporte = idCuentaaporte;
		this.saldo = saldo;
		this.estadoCuenta = estadoCuenta;
		this.socios = socios;
	}

	@Id
	@Column(name = "ID_CUENTAAPORTE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCuentaaporte() {
		return this.idCuentaaporte;
	}

	public void setIdCuentaaporte(BigDecimal idCuentaaporte) {
		this.idCuentaaporte = idCuentaaporte;
	}

	@Column(name = "SALDO", nullable = false, precision = 18)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA", nullable = false)
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@Column(name = "ESTADO_CUENTA", nullable = false, length = 24,columnDefinition = "nvarchar2")
	public String getEstadoCuenta() {
		return this.estadoCuenta;
	}

	public void setEstadoCuenta(String estadoCuenta) {
		this.estadoCuenta = estadoCuenta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaAporte")
	public Set<Socio> getSocios() {
		return this.socios;
	}

	public void setSocios(Set socios) {
		this.socios = socios;
	}

}
