package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleHistorialCaja generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_HISTORIAL_CAJA", schema = "BDSISTEMAFINANCIERO")
public class DetalleHistorialCaja implements java.io.Serializable,Comparable<DetalleHistorialCaja> {

	private BigDecimal idDetalleHistorialCaja;
	private MonedaDenominacion monedaDenominacion;
	private HistorialCaja historialCaja;
	private int cantidad;

	public DetalleHistorialCaja() {
	}

	public DetalleHistorialCaja(BigDecimal idDetalleHistorialCaja,
			MonedaDenominacion monedaDenominacion, HistorialCaja historialCaja,
			int cantidad) {
		this.idDetalleHistorialCaja = idDetalleHistorialCaja;
		this.monedaDenominacion = monedaDenominacion;
		this.historialCaja = historialCaja;
		this.cantidad = cantidad;
	}

	@Id
	@Column(name = "ID_DETALLE_HISTORIAL_CAJA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDetalleHistorialCaja() {
		return this.idDetalleHistorialCaja;
	}

	public void setIdDetalleHistorialCaja(BigDecimal idDetalleHistorialCaja) {
		this.idDetalleHistorialCaja = idDetalleHistorialCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false)
	public MonedaDenominacion getMonedaDenominacion() {
		return this.monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_CAJA", nullable = false)
	public HistorialCaja getHistorialCaja() {
		return this.historialCaja;
	}

	public void setHistorialCaja(HistorialCaja historialCaja) {
		this.historialCaja = historialCaja;
	}

	@Column(name = "CANTIDAD", nullable = false, precision = 22, scale = 0)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Override
	public int compareTo(DetalleHistorialCaja o) {
		return this.monedaDenominacion.getValor().compareTo(o.getMonedaDenominacion().getValor());
	}

}
