package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleHistorialBoveda generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_HISTORIAL_BOVEDA", schema = "BDSISTEMAFINANCIERO")
public class DetalleHistorialBoveda implements java.io.Serializable {

	private BigDecimal idDetalleHistorialBoveda;
	private MonedaDenominacion monedaDenominacion;
	private HistorialBoveda historialBoveda;
	private BigInteger cantidad;

	public DetalleHistorialBoveda() {
	}

	public DetalleHistorialBoveda(BigDecimal idDetalleHistorialBoveda,
			MonedaDenominacion monedaDenominacion,
			HistorialBoveda historialBoveda, BigInteger cantidad) {
		this.idDetalleHistorialBoveda = idDetalleHistorialBoveda;
		this.monedaDenominacion = monedaDenominacion;
		this.historialBoveda = historialBoveda;
		this.cantidad = cantidad;
	}

	@Id
	@Column(name = "ID_DETALLE_HISTORIAL_BOVEDA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDetalleHistorialBoveda() {
		return this.idDetalleHistorialBoveda;
	}

	public void setIdDetalleHistorialBoveda(BigDecimal idDetalleHistorialBoveda) {
		this.idDetalleHistorialBoveda = idDetalleHistorialBoveda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false)
	public MonedaDenominacion getMonedaDenominacion() {
		return this.monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_BOVEDA", nullable = false)
	public HistorialBoveda getHistorialBoveda() {
		return this.historialBoveda;
	}

	public void setHistorialBoveda(HistorialBoveda historialBoveda) {
		this.historialBoveda = historialBoveda;
	}

	@Column(name = "CANTIDAD", nullable = false, precision = 22, scale = 0)
	public BigInteger getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigInteger cantidad) {
		this.cantidad = cantidad;
	}

}
