package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetalleTransaccionCaja generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_TRANSACCION_CAJA", schema = "BDSISTEMAFINANCIERO")
public class DetalleTransaccionCaja implements java.io.Serializable {

	private BigDecimal idDetalleTransaccionCaja;
	private BigDecimal cantidad;
	private BigDecimal valorMoneda;
	private String origenDetalle;
	private BigDecimal idOrigen;

	public DetalleTransaccionCaja() {
	}

	public DetalleTransaccionCaja(BigDecimal idDetalleTransaccionCaja) {
		this.idDetalleTransaccionCaja = idDetalleTransaccionCaja;
	}

	public DetalleTransaccionCaja(BigDecimal idDetalleTransaccionCaja,
			BigDecimal cantidad, BigDecimal valorMoneda, String origenDetalle,
			BigDecimal idOrigen) {
		this.idDetalleTransaccionCaja = idDetalleTransaccionCaja;
		this.cantidad = cantidad;
		this.valorMoneda = valorMoneda;
		this.origenDetalle = origenDetalle;
		this.idOrigen = idOrigen;
	}

	@Id
	@Column(name = "ID_DETALLE_TRANSACCION_CAJA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDetalleTransaccionCaja() {
		return this.idDetalleTransaccionCaja;
	}

	public void setIdDetalleTransaccionCaja(BigDecimal idDetalleTransaccionCaja) {
		this.idDetalleTransaccionCaja = idDetalleTransaccionCaja;
	}

	@Column(name = "CANTIDAD", precision = 22, scale = 0)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "VALOR_MONEDA", precision = 6)
	public BigDecimal getValorMoneda() {
		return this.valorMoneda;
	}

	public void setValorMoneda(BigDecimal valorMoneda) {
		this.valorMoneda = valorMoneda;
	}

	@Column(name = "ORIGEN_DETALLE", length = 40,columnDefinition = "nvarchar2")
	public String getOrigenDetalle() {
		return this.origenDetalle;
	}

	public void setOrigenDetalle(String origenDetalle) {
		this.origenDetalle = origenDetalle;
	}

	@Column(name = "ID_ORIGEN", precision = 22, scale = 0)
	public BigDecimal getIdOrigen() {
		return this.idOrigen;
	}

	public void setIdOrigen(BigDecimal idOrigen) {
		this.idOrigen = idOrigen;
	}

}
