package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "ROL", schema = "BDSISTEMAFINANCIERO")
public class Rol implements java.io.Serializable {

	private BigDecimal idRol;
	private String denominacion;
	private String descripcion;
	private BigDecimal estado;
	private Set usuarioRols = new HashSet(0);

	public Rol() {
	}

	public Rol(BigDecimal idRol, String denominacion, String descripcion,
			BigDecimal estado) {
		this.idRol = idRol;
		this.denominacion = denominacion;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	public Rol(BigDecimal idRol, String denominacion, String descripcion,
			BigDecimal estado, Set usuarioRols) {
		this.idRol = idRol;
		this.denominacion = denominacion;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioRols = usuarioRols;
	}

	@Id
	@Column(name = "ID_ROL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdRol() {
		return this.idRol;
	}

	public void setIdRol(BigDecimal idRol) {
		this.idRol = idRol;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 60)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 140)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(Set usuarioRols) {
		this.usuarioRols = usuarioRols;
	}

}
