package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Socio generated by hbm2java
 */
@Entity
@Table(name = "SOCIO", schema = "BDSISTEMAFINANCIERO")
public class Socio implements java.io.Serializable {

	private BigDecimal idSocio;
	private PersonaNatural personaNatural;
	private CuentaAporte cuentaAporte;
	private PersonaJuridica personaJuridica;
	private Date fechaInicio;
	private Date fechaFin;
	private BigDecimal estado;
	private Set cuentaBancarias = new HashSet(0);

	public Socio() {
	}

	public Socio(BigDecimal idSocio, CuentaAporte cuentaAporte,
			Date fechaInicio, BigDecimal estado) {
		this.idSocio = idSocio;
		this.cuentaAporte = cuentaAporte;
		this.fechaInicio = fechaInicio;
		this.estado = estado;
	}

	public Socio(BigDecimal idSocio, PersonaNatural personaNatural,
			CuentaAporte cuentaAporte, PersonaJuridica personaJuridica,
			Date fechaInicio, Date fechaFin, BigDecimal estado,
			Set cuentaBancarias) {
		this.idSocio = idSocio;
		this.personaNatural = personaNatural;
		this.cuentaAporte = cuentaAporte;
		this.personaJuridica = personaJuridica;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
		this.cuentaBancarias = cuentaBancarias;
	}

	@Id
	@Column(name = "ID_SOCIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSocio() {
		return this.idSocio;
	}

	public void setIdSocio(BigDecimal idSocio) {
		this.idSocio = idSocio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_APODERADO")
	public PersonaNatural getPersonaNatural() {
		return this.personaNatural;
	}

	public void setPersonaNatural(PersonaNatural personaNatural) {
		this.personaNatural = personaNatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTAAPORTE", nullable = false)
	public CuentaAporte getCuentaAporte() {
		return this.cuentaAporte;
	}

	public void setCuentaAporte(CuentaAporte cuentaAporte) {
		this.cuentaAporte = cuentaAporte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA_JURIDICA")
	public PersonaJuridica getPersonaJuridica() {
		return this.personaJuridica;
	}

	public void setPersonaJuridica(PersonaJuridica personaJuridica) {
		this.personaJuridica = personaJuridica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", nullable = false, length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socio")
	public Set<CuentaBancaria> getCuentaBancarias() {
		return this.cuentaBancarias;
	}

	public void setCuentaBancarias(Set cuentaBancarias) {
		this.cuentaBancarias = cuentaBancarias;
	}

}
