package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "SUCURSAL", schema = "BDSISTEMAFINANCIERO")
public class Sucursal implements java.io.Serializable {

	private BigDecimal idSucursal;
	private String denominacion;
	private String abreviatura;
	private BigDecimal estado;
	private Set agencias = new HashSet(0);

	public Sucursal() {
	}

	public Sucursal(BigDecimal idSucursal, String denominacion,
			BigDecimal estado) {
		this.idSucursal = idSucursal;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public Sucursal(BigDecimal idSucursal, String denominacion,
			String abreviatura, BigDecimal estado, Set agencias) {
		this.idSucursal = idSucursal;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.agencias = agencias;
	}

	@Id
	@Column(name = "ID_SUCURSAL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSucursal() {
		return this.idSucursal;
	}

	public void setIdSucursal(BigDecimal idSucursal) {
		this.idSucursal = idSucursal;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 100)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ABREVIATURA", length = 20)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Agencia> getAgencias() {
		return this.agencias;
	}

	public void setAgencias(Set agencias) {
		this.agencias = agencias;
	}

}
