package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "TIPO_DOCUMENTO", schema = "BDSISTEMAFINANCIERO")
public class TipoDocumento implements java.io.Serializable {

	private BigDecimal idTipoDocumento;
	private String denominacion;
	private String abreviatura;
	private String tipoPersona;
	private BigDecimal numeroCaracteres;
	private BigDecimal estado;
	private Set personaNaturals = new HashSet(0);
	private Set personaJuridicas = new HashSet(0);

	public TipoDocumento() {
	}

	public TipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public TipoDocumento(BigDecimal idTipoDocumento, String denominacion,
			String abreviatura, String tipoPersona,
			BigDecimal numeroCaracteres, BigDecimal estado,
			Set personaNaturals, Set personaJuridicas) {
		this.idTipoDocumento = idTipoDocumento;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.tipoPersona = tipoPersona;
		this.numeroCaracteres = numeroCaracteres;
		this.estado = estado;
		this.personaNaturals = personaNaturals;
		this.personaJuridicas = personaJuridicas;
	}

	@Id
	@Column(name = "ID_TIPO_DOCUMENTO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	@Column(name = "DENOMINACION", length = 60)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ABREVIATURA", length = 40)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "TIPO_PERSONA", length = 40)
	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	@Column(name = "NUMERO_CARACTERES", precision = 22, scale = 0)
	public BigDecimal getNumeroCaracteres() {
		return this.numeroCaracteres;
	}

	public void setNumeroCaracteres(BigDecimal numeroCaracteres) {
		this.numeroCaracteres = numeroCaracteres;
	}

	@Column(name = "ESTADO", precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<PersonaNatural> getPersonaNaturals() {
		return this.personaNaturals;
	}

	public void setPersonaNaturals(Set personaNaturals) {
		this.personaNaturals = personaNaturals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set<PersonaJuridica> getPersonaJuridicas() {
		return this.personaJuridicas;
	}

	public void setPersonaJuridicas(Set personaJuridicas) {
		this.personaJuridicas = personaJuridicas;
	}

}
