package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCuentaBancaria generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CUENTA_BANCARIA", schema = "BDSISTEMAFINANCIERO")
public class TipoCuentaBancaria implements java.io.Serializable {

	private BigDecimal idTipoCuentaBancaria;
	private String denominacion;
	private String abreviatura;
	private BigDecimal estado;
	private Set cuentaBancarias = new HashSet(0);

	public TipoCuentaBancaria() {
	}

	public TipoCuentaBancaria(BigDecimal idTipoCuentaBancaria,
			String denominacion, BigDecimal estado) {
		this.idTipoCuentaBancaria = idTipoCuentaBancaria;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public TipoCuentaBancaria(BigDecimal idTipoCuentaBancaria,
			String denominacion, String abreviatura, BigDecimal estado,
			Set cuentaBancarias) {
		this.idTipoCuentaBancaria = idTipoCuentaBancaria;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.cuentaBancarias = cuentaBancarias;
	}

	@Id
	@Column(name = "ID_TIPO_CUENTA_BANCARIA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTipoCuentaBancaria() {
		return this.idTipoCuentaBancaria;
	}

	public void setIdTipoCuentaBancaria(BigDecimal idTipoCuentaBancaria) {
		this.idTipoCuentaBancaria = idTipoCuentaBancaria;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 60)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "ABREVIATURA", length = 20)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCuentaBancaria")
	public Set<CuentaBancaria> getCuentaBancarias() {
		return this.cuentaBancarias;
	}

	public void setCuentaBancarias(Set cuentaBancarias) {
		this.cuentaBancarias = cuentaBancarias;
	}

}
