package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "TIPO_SERVICIO", schema = "BDSISTEMAFINANCIERO")
@XmlRootElement(name = "tipoServicio")
@XmlAccessorType(XmlAccessType.NONE)
public class TipoServicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private BigInteger idTipoServicio;
	private String denominacion;
	private String descripcion;
	private Set servicios = new HashSet(0);

	public TipoServicio() {
	}	

	@XmlElement(name="id")
	@Id
	@Column(name = "ID_TIPO_SERVICIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdTipoServicio() {
		return this.idTipoServicio;
	}

	public void setIdTipoServicio(BigInteger idTipoServicio) {
		this.idTipoServicio = idTipoServicio;
	}

	@XmlElement
	@Column(name = "DENOMINACION", length = 30, columnDefinition = "nvarchar2")
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@XmlElement
	@Column(name = "DESCRIPCION", length = 50, columnDefinition = "nvarchar2")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}	

	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set servicios) {
		this.servicios = servicios;
	}
	
}
