package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titular generated by hbm2java
 */
@Entity
@Table(name = "TITULAR", schema = "BDSISTEMAFINANCIERO")
public class Titular implements java.io.Serializable {

	private BigDecimal idTitular;
	private PersonaNatural personaNatural;
	private CuentaBancaria cuentaBancaria;
	private Date fechaInicio;
	private Date fechaFin;
	private BigDecimal estado;

	public Titular() {
	}

	public Titular(BigDecimal idTitular, PersonaNatural personaNatural,
			CuentaBancaria cuentaBancaria, Date fechaInicio, BigDecimal estado) {
		this.idTitular = idTitular;
		this.personaNatural = personaNatural;
		this.cuentaBancaria = cuentaBancaria;
		this.fechaInicio = fechaInicio;
		this.estado = estado;
	}

	public Titular(BigDecimal idTitular, PersonaNatural personaNatural,
			CuentaBancaria cuentaBancaria, Date fechaInicio, Date fechaFin,
			BigDecimal estado) {
		this.idTitular = idTitular;
		this.personaNatural = personaNatural;
		this.cuentaBancaria = cuentaBancaria;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}

	@Id
	@Column(name = "ID_TITULAR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTitular() {
		return this.idTitular;
	}

	public void setIdTitular(BigDecimal idTitular) {
		this.idTitular = idTitular;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PERSONA_NATURAL", nullable = false)
	public PersonaNatural getPersonaNatural() {
		return this.personaNatural;
	}

	public void setPersonaNatural(PersonaNatural personaNatural) {
		this.personaNatural = personaNatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTA_BANCARIA", nullable = false)
	public CuentaBancaria getCuentaBancaria() {
		return this.cuentaBancaria;
	}

	public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
		this.cuentaBancaria = cuentaBancaria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", nullable = false, length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

}
