package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TrabajadorUsuario generated by hbm2java
 */
@Entity
@Table(name = "TRABAJADOR_USUARIO", schema = "BDSISTEMAFINANCIERO")
public class TrabajadorUsuario implements java.io.Serializable {

	private TrabajadorUsuarioId id;
	private Usuario usuario;
	private Trabajador trabajador;

	public TrabajadorUsuario() {
	}

	public TrabajadorUsuario(TrabajadorUsuarioId id, Usuario usuario,
			Trabajador trabajador) {
		this.id = id;
		this.usuario = usuario;
		this.trabajador = trabajador;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTrabajador", column = @Column(name = "ID_TRABAJADOR", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "ID_USUARIO", nullable = false, precision = 22, scale = 0)) })
	public TrabajadorUsuarioId getId() {
		return this.id;
	}

	public void setId(TrabajadorUsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USUARIO", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne
	@JoinColumn(name = "ID_TRABAJADOR", nullable = false, insertable = false, updatable = false)
	public Trabajador getTrabajador() {
		return this.trabajador;
	}

	public void setTrabajador(Trabajador trabajador) {
		this.trabajador = trabajador;
	}

}
