package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrabajadorUsuarioId generated by hbm2java
 */
@Embeddable
public class TrabajadorUsuarioId implements java.io.Serializable {

	private BigDecimal idTrabajador;
	private BigDecimal idUsuario;

	public TrabajadorUsuarioId() {
	}

	public TrabajadorUsuarioId(BigDecimal idTrabajador, BigDecimal idUsuario) {
		this.idTrabajador = idTrabajador;
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_TRABAJADOR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTrabajador() {
		return this.idTrabajador;
	}

	public void setIdTrabajador(BigDecimal idTrabajador) {
		this.idTrabajador = idTrabajador;
	}

	@Column(name = "ID_USUARIO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(BigDecimal idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrabajadorUsuarioId))
			return false;
		TrabajadorUsuarioId castOther = (TrabajadorUsuarioId) other;

		return ((this.getIdTrabajador() == castOther.getIdTrabajador()) || (this
				.getIdTrabajador() != null
				&& castOther.getIdTrabajador() != null && this
				.getIdTrabajador().equals(castOther.getIdTrabajador())))
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
						.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this
						.getIdUsuario().equals(castOther.getIdUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdTrabajador() == null ? 0 : this.getIdTrabajador()
						.hashCode());
		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		return result;
	}

}
