package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransaccionBancaria generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BANCARIA", schema = "BDSISTEMAFINANCIERO")
public class TransaccionBancaria implements java.io.Serializable {

	private BigDecimal idTransaccionBancaria;
	private HistorialCaja historialCaja;
	private CuentaBancaria cuentaBancaria;
	private Date fecha;
	private Date hora;
	private BigDecimal numeroOperacion;
	private BigDecimal monto;
	private String referencia;
	private BigDecimal estado;
	private BigDecimal saldoDisponible;
	private String tipoTransaccion;
	private String observacion;

	public TransaccionBancaria() {
	}

	public TransaccionBancaria(BigDecimal idTransaccionBancaria,
			HistorialCaja historialCaja, CuentaBancaria cuentaBancaria,
			Date fecha, Date hora, BigDecimal numeroOperacion,
			BigDecimal monto, BigDecimal estado, BigDecimal saldoDisponible,
			String tipoTransaccion) {
		this.idTransaccionBancaria = idTransaccionBancaria;
		this.historialCaja = historialCaja;
		this.cuentaBancaria = cuentaBancaria;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.monto = monto;
		this.estado = estado;
		this.saldoDisponible = saldoDisponible;
		this.tipoTransaccion = tipoTransaccion;
	}

	public TransaccionBancaria(BigDecimal idTransaccionBancaria,
			HistorialCaja historialCaja, CuentaBancaria cuentaBancaria,
			Date fecha, Date hora, BigDecimal numeroOperacion,
			BigDecimal monto, String referencia, BigDecimal estado,
			BigDecimal saldoDisponible, String tipoTransaccion,
			String observacion) {
		this.idTransaccionBancaria = idTransaccionBancaria;
		this.historialCaja = historialCaja;
		this.cuentaBancaria = cuentaBancaria;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.monto = monto;
		this.referencia = referencia;
		this.estado = estado;
		this.saldoDisponible = saldoDisponible;
		this.tipoTransaccion = tipoTransaccion;
		this.observacion = observacion;
	}

	@Id
	@Column(name = "ID_TRANSACCION_BANCARIA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTransaccionBancaria() {
		return this.idTransaccionBancaria;
	}

	public void setIdTransaccionBancaria(BigDecimal idTransaccionBancaria) {
		this.idTransaccionBancaria = idTransaccionBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_CAJA", nullable = false)
	public HistorialCaja getHistorialCaja() {
		return this.historialCaja;
	}

	public void setHistorialCaja(HistorialCaja historialCaja) {
		this.historialCaja = historialCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTA_BANCARIA", nullable = false)
	public CuentaBancaria getCuentaBancaria() {
		return this.cuentaBancaria;
	}

	public void setCuentaBancaria(CuentaBancaria cuentaBancaria) {
		this.cuentaBancaria = cuentaBancaria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "NUMERO_OPERACION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumeroOperacion() {
		return this.numeroOperacion;
	}

	public void setNumeroOperacion(BigDecimal numeroOperacion) {
		this.numeroOperacion = numeroOperacion;
	}

	@Column(name = "MONTO", nullable = false, precision = 18)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "REFERENCIA", length = 140, columnDefinition = "nvarchar2")
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@Column(name = "SALDO_DISPONIBLE", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponible() {
		return this.saldoDisponible;
	}

	public void setSaldoDisponible(BigDecimal saldoDisponible) {
		this.saldoDisponible = saldoDisponible;
	}

	@Column(name = "TIPO_TRANSACCION", nullable = false, length = 40, columnDefinition = "nvarchar2")
	public String getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(String tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

	@Column(name = "OBSERVACION", length = 100, columnDefinition = "nvarchar2")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
