package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransaccionBovedaOtro generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_OTRO", schema = "BDSISTEMAFINANCIERO")
public class TransaccionBovedaOtro implements java.io.Serializable {

	private BigDecimal idTransaccionBovedaOtro;
	private Entidad entidad;
	private HistorialBoveda historialBoveda;
	private Date fecha;
	private Serializable hora;
	private BigDecimal saldoDisponible;
	private String observacion;
	private BigDecimal estado;
	private String tipoTransaccion;
	private Set transaccionBovedaOtroDetalls = new HashSet(0);

	public TransaccionBovedaOtro() {
	}

	public TransaccionBovedaOtro(BigDecimal idTransaccionBovedaOtro,
			Entidad entidad, HistorialBoveda historialBoveda, Date fecha,
			Serializable hora, BigDecimal saldoDisponible, BigDecimal estado,
			String tipoTransaccion) {
		this.idTransaccionBovedaOtro = idTransaccionBovedaOtro;
		this.entidad = entidad;
		this.historialBoveda = historialBoveda;
		this.fecha = fecha;
		this.hora = hora;
		this.saldoDisponible = saldoDisponible;
		this.estado = estado;
		this.tipoTransaccion = tipoTransaccion;
	}

	public TransaccionBovedaOtro(BigDecimal idTransaccionBovedaOtro,
			Entidad entidad, HistorialBoveda historialBoveda, Date fecha,
			Serializable hora, BigDecimal saldoDisponible, String observacion,
			BigDecimal estado, String tipoTransaccion,
			Set transaccionBovedaOtroDetalls) {
		this.idTransaccionBovedaOtro = idTransaccionBovedaOtro;
		this.entidad = entidad;
		this.historialBoveda = historialBoveda;
		this.fecha = fecha;
		this.hora = hora;
		this.saldoDisponible = saldoDisponible;
		this.observacion = observacion;
		this.estado = estado;
		this.tipoTransaccion = tipoTransaccion;
		this.transaccionBovedaOtroDetalls = transaccionBovedaOtroDetalls;
	}

	@Id
	@Column(name = "ID_TRANSACCION_BOVEDA_OTRO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTransaccionBovedaOtro() {
		return this.idTransaccionBovedaOtro;
	}

	public void setIdTransaccionBovedaOtro(BigDecimal idTransaccionBovedaOtro) {
		this.idTransaccionBovedaOtro = idTransaccionBovedaOtro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ENTIDAD", nullable = false)
	public Entidad getEntidad() {
		return this.entidad;
	}

	public void setEntidad(Entidad entidad) {
		this.entidad = entidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_BOVEDA", nullable = false)
	public HistorialBoveda getHistorialBoveda() {
		return this.historialBoveda;
	}

	public void setHistorialBoveda(HistorialBoveda historialBoveda) {
		this.historialBoveda = historialBoveda;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Serializable getHora() {
		return this.hora;
	}

	public void setHora(Serializable hora) {
		this.hora = hora;
	}

	@Column(name = "SALDO_DISPONIBLE", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponible() {
		return this.saldoDisponible;
	}

	public void setSaldoDisponible(BigDecimal saldoDisponible) {
		this.saldoDisponible = saldoDisponible;
	}

	@Column(name = "OBSERVACION", length = 140)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@Column(name = "TIPO_TRANSACCION", nullable = false, length = 40)
	public String getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(String tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaccionBovedaOtro")
	public Set<TransaccionBovedaOtroDetall> getTransaccionBovedaOtroDetalls() {
		return this.transaccionBovedaOtroDetalls;
	}

	public void setTransaccionBovedaOtroDetalls(Set transaccionBovedaOtroDetalls) {
		this.transaccionBovedaOtroDetalls = transaccionBovedaOtroDetalls;
	}

}
