package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransaccionBovedaOtroDetall generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_BOVEDA_OTRO_DETALL", schema = "BDSISTEMAFINANCIERO")
public class TransaccionBovedaOtroDetall implements java.io.Serializable {

	private BigDecimal idTransaccionBovedaOtroDet;
	private MonedaDenominacion monedaDenominacion;
	private TransaccionBovedaOtro transaccionBovedaOtro;
	private BigDecimal cantidad;

	public TransaccionBovedaOtroDetall() {
	}

	public TransaccionBovedaOtroDetall(BigDecimal idTransaccionBovedaOtroDet,
			MonedaDenominacion monedaDenominacion,
			TransaccionBovedaOtro transaccionBovedaOtro, BigDecimal cantidad) {
		this.idTransaccionBovedaOtroDet = idTransaccionBovedaOtroDet;
		this.monedaDenominacion = monedaDenominacion;
		this.transaccionBovedaOtro = transaccionBovedaOtro;
		this.cantidad = cantidad;
	}

	@Id
	@Column(name = "ID_TRANSACCION_BOVEDA_OTRO_DET", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTransaccionBovedaOtroDet() {
		return this.idTransaccionBovedaOtroDet;
	}

	public void setIdTransaccionBovedaOtroDet(
			BigDecimal idTransaccionBovedaOtroDet) {
		this.idTransaccionBovedaOtroDet = idTransaccionBovedaOtroDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DENOMINACION", nullable = false)
	public MonedaDenominacion getMonedaDenominacion() {
		return this.monedaDenominacion;
	}

	public void setMonedaDenominacion(MonedaDenominacion monedaDenominacion) {
		this.monedaDenominacion = monedaDenominacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TRANSACCION_BOVEDA_OTRO", nullable = false)
	public TransaccionBovedaOtro getTransaccionBovedaOtro() {
		return this.transaccionBovedaOtro;
	}

	public void setTransaccionBovedaOtro(
			TransaccionBovedaOtro transaccionBovedaOtro) {
		this.transaccionBovedaOtro = transaccionBovedaOtro;
	}

	@Column(name = "CANTIDAD", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

}
