package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.ventura.sistemafinanciero.entity.type.Tipotransaccionbancaria;

/**
 * TransaccionCuentaAporte generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_CUENTA_APORTE", schema = "BDSISTEMAFINANCIERO")
@SequenceGenerator(name="secuencia_transaccion_aporte", initialValue=1, allocationSize=1, sequenceName="TRANSACCION_SEQUENCE")
public class TransaccionCuentaAporte implements java.io.Serializable {

	private BigInteger idTransaccionCuentaAporte;
	private HistorialCaja historialCaja;
	private CuentaAporte cuentaAporte;
	private Date fecha;
	private Date hora;
	private BigInteger numeroOperacion;
	private BigDecimal monto;
	private int mesAfecta;
	private int anioAfecta;
	private int estado;
	private BigDecimal saldoDisponible;
	private String referencia;
	private String observacion;
	private Tipotransaccionbancaria tipoTransaccion;

	public TransaccionCuentaAporte() {
	}

	public TransaccionCuentaAporte(BigInteger idTransaccionCuentaAporte,
			HistorialCaja historialCaja, Date fecha, Date hora,
			BigInteger numeroOperacion, BigDecimal monto, int anioAfecta,
			boolean estado, BigDecimal saldoDisponible,
			Tipotransaccionbancaria tipoTransaccion) {
		this.idTransaccionCuentaAporte = idTransaccionCuentaAporte;
		this.historialCaja = historialCaja;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.monto = monto;
		this.anioAfecta = anioAfecta;
		this.estado = (estado ? 1 : 0);
		this.saldoDisponible = saldoDisponible;
		this.tipoTransaccion = tipoTransaccion;
	}

	public TransaccionCuentaAporte(BigInteger idTransaccionCuentaAporte,
			HistorialCaja historialCaja, Date fecha, Date hora,
			BigInteger numeroOperacion, BigDecimal monto, int mesAfecta,
			int anioAfecta, boolean estado, BigDecimal saldoDisponible,
			String referencia, String observacion,
			Tipotransaccionbancaria tipoTransaccion) {
		this.idTransaccionCuentaAporte = idTransaccionCuentaAporte;
		this.historialCaja = historialCaja;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.monto = monto;
		this.mesAfecta = mesAfecta;
		this.anioAfecta = anioAfecta;
		this.estado = (estado ? 1 : 0);
		this.saldoDisponible = saldoDisponible;
		this.referencia = referencia;
		this.observacion = observacion;
		this.tipoTransaccion = tipoTransaccion;
	}
	
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="secuencia_transaccion_aporte")
	@Id
	@Column(name = "ID_TRANSACCION_CUENTA_APORTE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdTransaccionCuentaAporte() {
		return this.idTransaccionCuentaAporte;
	}

	public void setIdTransaccionCuentaAporte(
			BigInteger idTransaccionCuentaAporte) {
		this.idTransaccionCuentaAporte = idTransaccionCuentaAporte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_CAJA", nullable = false)
	public HistorialCaja getHistorialCaja() {
		return this.historialCaja;
	}

	public void setHistorialCaja(HistorialCaja historialCaja) {
		this.historialCaja = historialCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTAAPORTE", nullable = false)
	public CuentaAporte getCuentaAporte() {
		return this.cuentaAporte;
	}

	public void setCuentaAporte(CuentaAporte cuentaAporte) {
		this.cuentaAporte = cuentaAporte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "NUMERO_OPERACION", nullable = false, precision = 22, scale = 0)
	public BigInteger getNumeroOperacion() {
		return this.numeroOperacion;
	}

	public void setNumeroOperacion(BigInteger numeroOperacion) {
		this.numeroOperacion = numeroOperacion;
	}

	@Column(name = "MONTO", nullable = false, precision = 18)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "MES_AFECTA", precision = 22, scale = 0)
	public int getMesAfecta() {
		return this.mesAfecta;
	}

	public void setMesAfecta(int mesAfecta) {
		this.mesAfecta = mesAfecta;
	}

	@Column(name = "ANIO_AFECTA", nullable = false, precision = 22, scale = 0)
	public int getAnioAfecta() {
		return this.anioAfecta;
	}

	public void setAnioAfecta(int anioAfecta) {
		this.anioAfecta = anioAfecta;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public boolean getEstado() {
		return (this.estado == 1 ? true : false);
	}

	public void setEstado(boolean estado) {
		this.estado = (estado ? 1 : 0);
	}

	@Column(name = "SALDO_DISPONIBLE", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponible() {
		return this.saldoDisponible;
	}

	public void setSaldoDisponible(BigDecimal saldoDisponible) {
		this.saldoDisponible = saldoDisponible;
	}

	@Column(name = "REFERENCIA", length = 140, columnDefinition = "nvarchar2")
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "OBSERVACION", length = 100, columnDefinition = "nvarchar2")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Enumerated(value = EnumType.STRING)
	@Column(name = "TIPO_TRANSACCION", nullable = false, length = 16, columnDefinition = "nvarchar2")
	public Tipotransaccionbancaria getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(Tipotransaccionbancaria tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

}
