package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransaccionCompraVenta generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_COMPRA_VENTA", schema = "BDSISTEMAFINANCIERO")
public class TransaccionCompraVenta implements java.io.Serializable {

	private BigDecimal idTransaccionCompraVenta;
	private HistorialCaja historialCaja;
	private Moneda monedaByIdMonedaRecibido;
	private Moneda monedaByIdMonedaEntregado;
	private Date fecha;
	private Serializable hora;
	private BigDecimal numeroOperacion;
	private BigDecimal montoRecibido;
	private BigDecimal montoEntregado;
	private BigDecimal tipoCambio;
	private String referencia;
	private BigDecimal estado;
	private String observacion;
	private String tipoTransaccion;

	public TransaccionCompraVenta() {
	}

	public TransaccionCompraVenta(BigDecimal idTransaccionCompraVenta,
			HistorialCaja historialCaja, Moneda monedaByIdMonedaRecibido,
			Moneda monedaByIdMonedaEntregado, Date fecha, Serializable hora,
			BigDecimal numeroOperacion, BigDecimal montoRecibido,
			BigDecimal montoEntregado, BigDecimal tipoCambio,
			BigDecimal estado, String tipoTransaccion) {
		this.idTransaccionCompraVenta = idTransaccionCompraVenta;
		this.historialCaja = historialCaja;
		this.monedaByIdMonedaRecibido = monedaByIdMonedaRecibido;
		this.monedaByIdMonedaEntregado = monedaByIdMonedaEntregado;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.montoRecibido = montoRecibido;
		this.montoEntregado = montoEntregado;
		this.tipoCambio = tipoCambio;
		this.estado = estado;
		this.tipoTransaccion = tipoTransaccion;
	}

	public TransaccionCompraVenta(BigDecimal idTransaccionCompraVenta,
			HistorialCaja historialCaja, Moneda monedaByIdMonedaRecibido,
			Moneda monedaByIdMonedaEntregado, Date fecha, Serializable hora,
			BigDecimal numeroOperacion, BigDecimal montoRecibido,
			BigDecimal montoEntregado, BigDecimal tipoCambio,
			String referencia, BigDecimal estado, String observacion,
			String tipoTransaccion) {
		this.idTransaccionCompraVenta = idTransaccionCompraVenta;
		this.historialCaja = historialCaja;
		this.monedaByIdMonedaRecibido = monedaByIdMonedaRecibido;
		this.monedaByIdMonedaEntregado = monedaByIdMonedaEntregado;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.montoRecibido = montoRecibido;
		this.montoEntregado = montoEntregado;
		this.tipoCambio = tipoCambio;
		this.referencia = referencia;
		this.estado = estado;
		this.observacion = observacion;
		this.tipoTransaccion = tipoTransaccion;
	}

	@Id
	@Column(name = "ID_TRANSACCION_COMPRA_VENTA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTransaccionCompraVenta() {
		return this.idTransaccionCompraVenta;
	}

	public void setIdTransaccionCompraVenta(BigDecimal idTransaccionCompraVenta) {
		this.idTransaccionCompraVenta = idTransaccionCompraVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_CAJA", nullable = false)
	public HistorialCaja getHistorialCaja() {
		return this.historialCaja;
	}

	public void setHistorialCaja(HistorialCaja historialCaja) {
		this.historialCaja = historialCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_RECIBIDO", nullable = false)
	public Moneda getMonedaByIdMonedaRecibido() {
		return this.monedaByIdMonedaRecibido;
	}

	public void setMonedaByIdMonedaRecibido(Moneda monedaByIdMonedaRecibido) {
		this.monedaByIdMonedaRecibido = monedaByIdMonedaRecibido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_ENTREGADO", nullable = false)
	public Moneda getMonedaByIdMonedaEntregado() {
		return this.monedaByIdMonedaEntregado;
	}

	public void setMonedaByIdMonedaEntregado(Moneda monedaByIdMonedaEntregado) {
		this.monedaByIdMonedaEntregado = monedaByIdMonedaEntregado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Serializable getHora() {
		return this.hora;
	}

	public void setHora(Serializable hora) {
		this.hora = hora;
	}

	@Column(name = "NUMERO_OPERACION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumeroOperacion() {
		return this.numeroOperacion;
	}

	public void setNumeroOperacion(BigDecimal numeroOperacion) {
		this.numeroOperacion = numeroOperacion;
	}

	@Column(name = "MONTO_RECIBIDO", nullable = false, precision = 18)
	public BigDecimal getMontoRecibido() {
		return this.montoRecibido;
	}

	public void setMontoRecibido(BigDecimal montoRecibido) {
		this.montoRecibido = montoRecibido;
	}

	@Column(name = "MONTO_ENTREGADO", nullable = false, precision = 18)
	public BigDecimal getMontoEntregado() {
		return this.montoEntregado;
	}

	public void setMontoEntregado(BigDecimal montoEntregado) {
		this.montoEntregado = montoEntregado;
	}

	@Column(name = "TIPO_CAMBIO", nullable = false, precision = 5, scale = 3)
	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	@Column(name = "REFERENCIA", length = 140)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@Column(name = "OBSERVACION", length = 100)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "TIPO_TRANSACCION", nullable = false, length = 12)
	public String getTipoTransaccion() {
		return this.tipoTransaccion;
	}

	public void setTipoTransaccion(String tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}

}
