package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransferenciaBancaria generated by hbm2java
 */
@Entity
@Table(name = "TRANSFERENCIA_BANCARIA", schema = "BDSISTEMAFINANCIERO")
public class TransferenciaBancaria implements java.io.Serializable {

	private BigDecimal idTransferenciaBancaria;
	private HistorialCaja historialCaja;
	private CuentaBancaria cuentaBancariaByIdCuentaBancariaOrigen;
	private CuentaBancaria cuentaBancariaByIdCuentaBancariaDestino;
	private Date fecha;
	private Date hora;
	private BigDecimal numeroOperacion;
	private BigDecimal monto;
	private String referencia;
	private BigDecimal saldoDisponibleOrigen;
	private BigDecimal saldoDisponibleDestino;
	private BigDecimal estado;
	private String observacion;

	public TransferenciaBancaria() {
	}

	public TransferenciaBancaria(BigDecimal idTransferenciaBancaria,
			HistorialCaja historialCaja,
			CuentaBancaria cuentaBancariaByIdCuentaBancariaOrigen,
			CuentaBancaria cuentaBancariaByIdCuentaBancariaDestino, Date fecha,
			Date hora, BigDecimal numeroOperacion, BigDecimal monto,
			BigDecimal saldoDisponibleOrigen,
			BigDecimal saldoDisponibleDestino, BigDecimal estado) {
		this.idTransferenciaBancaria = idTransferenciaBancaria;
		this.historialCaja = historialCaja;
		this.cuentaBancariaByIdCuentaBancariaOrigen = cuentaBancariaByIdCuentaBancariaOrigen;
		this.cuentaBancariaByIdCuentaBancariaDestino = cuentaBancariaByIdCuentaBancariaDestino;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.monto = monto;
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
		this.saldoDisponibleDestino = saldoDisponibleDestino;
		this.estado = estado;
	}

	public TransferenciaBancaria(BigDecimal idTransferenciaBancaria,
			HistorialCaja historialCaja,
			CuentaBancaria cuentaBancariaByIdCuentaBancariaOrigen,
			CuentaBancaria cuentaBancariaByIdCuentaBancariaDestino, Date fecha,
			Date hora, BigDecimal numeroOperacion, BigDecimal monto,
			String referencia, BigDecimal saldoDisponibleOrigen,
			BigDecimal saldoDisponibleDestino, BigDecimal estado,
			String observacion) {
		this.idTransferenciaBancaria = idTransferenciaBancaria;
		this.historialCaja = historialCaja;
		this.cuentaBancariaByIdCuentaBancariaOrigen = cuentaBancariaByIdCuentaBancariaOrigen;
		this.cuentaBancariaByIdCuentaBancariaDestino = cuentaBancariaByIdCuentaBancariaDestino;
		this.fecha = fecha;
		this.hora = hora;
		this.numeroOperacion = numeroOperacion;
		this.monto = monto;
		this.referencia = referencia;
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
		this.saldoDisponibleDestino = saldoDisponibleDestino;
		this.estado = estado;
		this.observacion = observacion;
	}

	@Id
	@Column(name = "ID_TRANSFERENCIA_BANCARIA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTransferenciaBancaria() {
		return this.idTransferenciaBancaria;
	}

	public void setIdTransferenciaBancaria(BigDecimal idTransferenciaBancaria) {
		this.idTransferenciaBancaria = idTransferenciaBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HISTORIAL_CAJA", nullable = false)
	public HistorialCaja getHistorialCaja() {
		return this.historialCaja;
	}

	public void setHistorialCaja(HistorialCaja historialCaja) {
		this.historialCaja = historialCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTA_BANCARIA_ORIGEN", nullable = false)
	public CuentaBancaria getCuentaBancariaByIdCuentaBancariaOrigen() {
		return this.cuentaBancariaByIdCuentaBancariaOrigen;
	}

	public void setCuentaBancariaByIdCuentaBancariaOrigen(
			CuentaBancaria cuentaBancariaByIdCuentaBancariaOrigen) {
		this.cuentaBancariaByIdCuentaBancariaOrigen = cuentaBancariaByIdCuentaBancariaOrigen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CUENTA_BANCARIA_DESTINO", nullable = false)
	public CuentaBancaria getCuentaBancariaByIdCuentaBancariaDestino() {
		return this.cuentaBancariaByIdCuentaBancariaDestino;
	}

	public void setCuentaBancariaByIdCuentaBancariaDestino(
			CuentaBancaria cuentaBancariaByIdCuentaBancariaDestino) {
		this.cuentaBancariaByIdCuentaBancariaDestino = cuentaBancariaByIdCuentaBancariaDestino;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "NUMERO_OPERACION", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNumeroOperacion() {
		return this.numeroOperacion;
	}

	public void setNumeroOperacion(BigDecimal numeroOperacion) {
		this.numeroOperacion = numeroOperacion;
	}

	@Column(name = "MONTO", nullable = false, precision = 18)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "REFERENCIA", length = 100,columnDefinition = "nvarchar2")
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "SALDO_DISPONIBLE_ORIGEN", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponibleOrigen() {
		return this.saldoDisponibleOrigen;
	}

	public void setSaldoDisponibleOrigen(BigDecimal saldoDisponibleOrigen) {
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
	}

	@Column(name = "SALDO_DISPONIBLE_DESTINO", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponibleDestino() {
		return this.saldoDisponibleDestino;
	}

	public void setSaldoDisponibleDestino(BigDecimal saldoDisponibleDestino) {
		this.saldoDisponibleDestino = saldoDisponibleDestino;
	}

	@Column(name = "ESTADO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	@Column(name = "OBSERVACION", length = 100,columnDefinition = "nvarchar2")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
