package org.ventura.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioRolId generated by hbm2java
 */
@Embeddable
public class UsuarioRolId implements java.io.Serializable {

	private BigDecimal idUsuario;
	private BigDecimal idRol;

	public UsuarioRolId() {
	}

	public UsuarioRolId(BigDecimal idUsuario, BigDecimal idRol) {
		this.idUsuario = idUsuario;
		this.idRol = idRol;
	}

	@Column(name = "ID_USUARIO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(BigDecimal idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_ROL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdRol() {
		return this.idRol;
	}

	public void setIdRol(BigDecimal idRol) {
		this.idRol = idRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioRolId))
			return false;
		UsuarioRolId castOther = (UsuarioRolId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
				.getIdUsuario() != null && castOther.getIdUsuario() != null && this
				.getIdUsuario().equals(castOther.getIdUsuario())))
				&& ((this.getIdRol() == castOther.getIdRol()) || (this
						.getIdRol() != null && castOther.getIdRol() != null && this
						.getIdRol().equals(castOther.getIdRol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result
				+ (getIdRol() == null ? 0 : this.getIdRol().hashCode());
		return result;
	}

}
